deploy_task:
  only_if: $CIRRUS_BRANCH == "master"
  container:
    image: node:latest
  env:
    DEPLOY_TOKEN: ENCRYPTED[d0b60a11a693454be3eaffcf678f90d6d574902d85ae22432e8c5017181c6e45ee10bf56041ab3af605e39c1d7f6274e]
  yarn_cache:
    folder: node_modules
    fingerprint_script: |
      cat package.json
      cat yarn.lock
    populate_script: yarn
  deploy_script: |
    ssh-keygen -R github.com
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    git config user.name "Cirrus CI"
    git config user.email "support@rdil.rocks"
    git remote rm origin
    git remote add origin ${DEPLOY_TOKEN}@github.com:RDIL/skyblock-minion-calc.git
    yarn deploy
