const minions = {
  cobblestone: "Cobblestone",
  wheat: "Wheat",
  carrot: "Carrot",
  potato: "Potato",
  pumpkin: "Pumpkin",
  melon: "Melon",
  mushroom: "Mushroom",
  cocoa_bean: "Cocoa Bean",
  cactus: "Cactus",
  desertcane: "Sugarcane",
  cow: "Cow",
  pig: "Pig",
  chicken: "Chicken",
  sheep: "Sheep",
  rabbit: "Rabbit",
  netherplant: "Nether Wart",
  coal: "Coal",
  iron: "Iron",
  gold: "gold",
  diamond: "diamond",
  lapislazuli: "Lapis Lazuli",
  emerald: "Emerald",
  redstone: "Redstone",
  netherquartz: "Nether Quartz",
  obsidian: "Obsidian",
  glowstone: "Glowstone",
  gravel: "Gravel",
  ice: "Ice",
  sand: "Sand",
  endstone: "Endstone",
  waterclay: "Clay",
  undead: "Zombie",
  undeadbones: "Skeleton",
  spider: "Spider",
  poisonedspider: "Cave Spider",
  creeper: "Creeper",
  enderman: "Enderman",
  ghast: "Ghast",
  slime: "Slime",
  blaze: "Blaze",
  netherslime: "Magma Cube",
  revenantboss: "Revenant",
  tarantulaboss: "Tarantula",
  fishing: "Fishing",
  oak: "Oak",
  birch: "Birch",
  darkoak: "Dark Oak",
  savannah: "Acatia",
  jungle: "Jungle"
}

export default minions
